<?php $this->includeLayout('Common', 'Header');?>

    <div id="container">
        This page is generated by function my_shutdownHandler(), the error(s) are not displayed for live site.
    </div>
    
<?php $this->includeLayout('Common', 'Footer');?>
